# @Author: Carlos Galeano
# @Date:   2026-02-06 15:11:57
# @Last Modified by:   Carlos Galeano
# @Last Modified time: 2026-02-17 10:17:19
services:
  api:   
    build: .
    working_dir: /app
    volumes:
      - .:/app
    image: fastapi-postgres:latest
    container_name: fastapi
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app
      #WEB_CONCURRENCY: "4"
      POSTGRES_HOST: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
      POSTGRES_PORT: "5432"
    ports:
      - "8000:8000"
    # networks:
    #   - bench-net
    extra_hosts:
        - "host.docker.internal:host-gateway"
    command: >
      uvicorn paquete.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app

  #networks:
  #bench-net:
   # external: true 

